CREATE TABLE category
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    is_complete BOOLEAN,
    category_id BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE category
    ADD CONSTRAINT uc_category_label UNIQUE (label);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);